[template]
src = "filebeat.yml.tmpl"
dest = "/etc/filebeat/filebeat.yml"
keys = [
    "/filebeat/logstash/hosts"
]
### Uncomment this in production servers
# reload_cmd = "/etc/init.d/filebeat restart"
