filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/local/apache2/logs/access_log

# output.console:
#   pretty: true

output.kafka:
  hosts: ["kafka:9092"]

  # message topic selection + partitioning
  topic: 'apache_access_log'
  partition.round_robin:
    reachable_only: false

  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
  bulk_max_size: 1
