version: '3'
services:
  sorry:
    build:
      context: ./sorry
      dockerfile: Dockerfile
      args:
        buildno: 1
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    depends_on:
      - "kafka"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - backend

  kafka:
    build: ./kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - backend
    depends_on:
      - "zookeeper"

  web:
    build: ./web
    ports:
      - "5000:5000"
    environment:
      KAFKA_HOSTS: kafka:9092
    networks:
      - backend
    depends_on:
      - "kafka"

networks:
  backend:
    driver: "bridge"
