version: '3'
services:
  #########################
  ### Local debug servers
  ### (Remove these in production servers!)
  #########################
  httpd:
    image: httpd
    network_mode: "host"
    volumes:
      - "logs:/usr/local/apache2/logs/demo/:rw"
      - "./sorry/httpd.conf:/usr/local/apache2/conf/httpd.conf"

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.4.0
    network_mode: "host"
    volumes:
      - "filebeat:/etc/filebeat/:ro"
      - "logs:/usr/local/apache2/logs/demo/:ro"
    command: filebeat -c /etc/filebeat/filebeat.yml
    depends_on:
      - "confd"
      - "kafka"
      - "elasticsearch"

  confd:
    image: rancher/confd
    network_mode: "host"
    command: -watch -backend consul -node 127.0.0.1:8500
    volumes:
      - "filebeat:/etc/filebeat/:rw"
      - "./sorry/confd/:/etc/confd/"
    depends_on:
      - "consul"


  #########################
  ### Production servers
  #########################
  consul:
    image: consul
    network_mode: "host"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: "host"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    depends_on:
      - "kafka"

  logstash:
    build:
      context: ./logstash
    environment:
      XPACK_MONITORING_ENABLED: "false"
    # ports:
    #   - "5044:5044"
    network_mode: "host"
    depends_on:
      - "kafka"

  zookeeper:
    image: wurstmeister/zookeeper
    # ports:
    #   - "2181:2181"
    network_mode: "host"

  kafka:
    build: ./kafka
    # ports:
    #   - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    network_mode: "host"
    depends_on:
      - "zookeeper"

  balancer:
    build: ./balancer
    # ports:
    #   - "80:80"
    network_mode: "host"

  web:
    build:
      context: ./web
    # ports:
    #   - "5001:5001"
    environment:
      KAFKA_HOSTS: localhost:9092
    network_mode: "host"
    depends_on:
      - "kafka"

  ssed:
    build:
      context: ./ssed
    # ports:
    #   - "5002:5002"
    environment:
        - BOOTSTRAP_SERVERS=localhost:9092
        - HOST=0.0.0.0:5002
    network_mode: "host"
    depends_on:
      - "kafka"

volumes:
  logs:
  filebeat:
  esdata:
