version: '3'
services:
  sorry1:
    build:
      context: ./sorry
      dockerfile: Dockerfile
      args:
        buildno: 1
    ports:
      - "10081:80"
    networks:
      - backend
    depends_on:
      - "kafka"
  sorry2:
    build:
      context: ./sorry
      dockerfile: Dockerfile
      args:
        buildno: 1
    ports:
      - "10082:80"
    networks:
      - backend
    depends_on:
      - "kafka"
  sorry3:
    build:
      context: ./sorry
      dockerfile: Dockerfile
      args:
        buildno: 1
    ports:
      - "10083:80"
    networks:
      - backend
    depends_on:
      - "kafka"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - backend

  kafka:
    build: ./kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - backend
    depends_on:
      - "zookeeper"

  web:
    build: ./web
    ports:
      - "5001:5000"
    environment:
      KAFKA_HOSTS: kafka:9092
    networks:
      - backend
    depends_on:
      - "kafka"

  ssed:
    build: ./ssed
    ports:
      - "5002:5000"
    environment:
        - BOOTSTRAP_SERVERS=kafka:9092
        - HOST=0.0.0.0:5000
    networks:
      - backend
    depends_on:
      - "kafka"

networks:
  backend:
    driver: "bridge"
