version: '3'
services:
  sorry:
    build:
      context: ./sorry
      args:
        buildno: 1
    # ports:
    #   - "10081:10081"
    network_mode: "host"
    depends_on:
      - "kafka"

  consul:
    image: consul
    network_mode: "host"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: "host"
    # volumes:
    #   - type: bind
    #     source: ./esdata/
    #     target: /usr/share/elasticsearch/data
    volumes:
      - esdata:/usr/share/elasticsearch/data
    depends_on:
      - "kafka"

  logstash:
    build:
      context: ./logstash
    environment:
      XPACK_MONITORING_ENABLED: "false"
    # ports:
    #   - "5044:5044"
    network_mode: "host"
    depends_on:
      - "kafka"

  zookeeper:
    image: wurstmeister/zookeeper
    # ports:
    #   - "2181:2181"
    network_mode: "host"

  kafka:
    build: ./kafka
    # ports:
    #   - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    network_mode: "host"
    depends_on:
      - "zookeeper"

  balancer:
    build: ./balancer
    # ports:
    #   - "80:80"
    network_mode: "host"

  web:
    build:
      context: ./web
    # ports:
    #   - "5001:5001"
    environment:
      KAFKA_HOSTS: localhost:9092
    network_mode: "host"
    depends_on:
      - "kafka"

  ssed:
    build:
      context: ./ssed
    # ports:
    #   - "5002:5002"
    environment:
        - BOOTSTRAP_SERVERS=localhost:9092
        - HOST=0.0.0.0:5002
    network_mode: "host"
    depends_on:
      - "kafka"

volumes:
  esdata:
